#!/usr/bin/env bash
# shellcheck disable=SC2129
set -euf -o pipefail

recipe_out_dir="${1:?}"
sdist_in_dir="${2:?}"

mkdir -p "$recipe_out_dir"

while read -r archive; do
  1>&2 echo "INFO: archive='$archive'"

  declare pkg_info_json
  pkg_info_json="$(pkginfo --json "$archive")"

  declare pkg_info_raw
  if [[ "$archive" == *.tar.gz ]]; then
    unset GZIP
    pkg_info_raw="$(tar \
      --wildcards '**/PKG-INFO' --use-compress-program=gzip \
      -xOzf \
      "$archive" \
    )"
  elif [[ "$archive" == *.zip ]]; then
    pkg_info_raw="$(unzip -p "$archive" '*/PKG-INFO')"
  else
    1>&2 printf -- "ERROR: Cannot extract license from python sdist.\n"
    1>&2 printf -- " -> Unsupported sdist file format: '%s'.\n" \
      "$archive"
    exit 1
  fi

  declare license_file
  if ! license_file="$( \
    echo "$pkg_info_raw" | grep -E '^License-File' \
    | head -n 1 | awk '{ print $2 }' | awk -v RS='\r' '{ print $1}' \
  )" || [[ -z "$license_file" ]]; then
    1>&2 printf -- "WARNING: Missing 'License-File' pkg info field.\n"
    1>&2 printf -- " -> Defaulting to 'LICENSE'.\n"
    license_file="LICENSE"
  fi

  1>&2 echo "DEBUG: license_file='$license_file'"

  exists_archive_file() {
    declare in_archive="${1?}"
    declare in_rel_filename="${2?}"
    if [[ "$in_archive" == *.tar.gz ]]; then
      tar \
        --wildcards "**/${in_rel_filename}" --use-compress-program=gzip \
        -xOzf \
        "$in_archive" \
        > /dev/null 2>&1
    elif [[ "$in_archive" == *.zip ]]; then
      unzip -p "$in_archive" "*/${in_rel_filename}" \
        > /dev/null 2>&1
    else
      false
    fi
  }

  extract_archive_file() {
    declare in_archive="${1?}"
    declare in_rel_filename="${2?}"
    if [[ "$in_archive" == *.tar.gz ]]; then
      tar \
        --wildcards "**/${in_rel_filename}" --use-compress-program=gzip \
        -xOzf \
        "$in_archive"
    elif [[ "$in_archive" == *.zip ]]; then
      unzip -p "$in_archive" "*/${in_rel_filename}"
    else
      false
    fi
  }

  declare license
  if ! license="$(extract_archive_file "$archive" "$license_file")"; then
    1>&2 printf -- "ERROR: Cannot extract license from python sdist.\n"
    1>&2 printf -- " -> Unsupported sdist file format: '%s'.\n" \
      "$archive"
    exit 1
  fi

  declare license_md5
  license_md5="$(echo "$license" | md5sum | awk '{print $1}')"

  declare src_uri_line
  src_uri_line="$( \
    pip hash --disable-pip-version-check --algorithm sha256 "$archive" \
    | grep -E "^--hash" \
    | sed -E \
      -e 's/^--hash\=([^\:]+)\:([0-9a-fA-F]+)$/SRC_URI[\1sum] = "\2"/g')"

  1>&2 echo "DEBUG: src_uri_line='$src_uri_line'"

  declare pkg_name
  pkg_name="$(echo "$pkg_info_json" | jq -j '.name')"

  declare pkg_version
  pkg_version="$(echo "$pkg_info_json" | jq -j '.version')"

  # Note the awk part is for getting rid of the license content
  # which is returned after 2 space characters by pkg_info json
  # representation.
  declare license_name
  license_name="$( \
    echo "$pkg_info_json" \
    | jq -j '.license' \
    | awk -F'  ' '{ print $1 }'
  )"

  if [[ "$license_name" == "null" ]]; then
    declare alt_license_name
    if alt_license_name="$( \
      echo "$pkg_info_json" \
      | jq -e -c -r '.classifiers[]' \
      | grep --ignore-case '^License' \
      | awk -F' :: ' '{ print $NF }' \
      | awk '{gsub(/^ +| +$/,"")} {print $0 }' \
    )"; then
      license_name="$alt_license_name"
      1>&2 echo "DEBUG: alt_license_name='$alt_license_name'"
    fi
  fi

  declare summary
  summary="$(echo "$pkg_info_json" | jq -j '.summary')"

  declare homepage
  homepage="$(echo "$pkg_info_json" | jq -j '.home_page')"

  declare project_urls
  project_urls="$(echo "$pkg_info_json" | jq -c -r '.project_urls[]?')"

  declare yocto_homepage
  if [[ "$homepage" != "null" ]]; then
    yocto_homepage="$homepage"
  else
    declare alt_homepage="null"
    declare prj_url_pattern
    for prj_url_pattern in '^homepage' '^repo' '^github repo'; do
      declare found
      if found="$( \
        echo "$project_urls" \
        | grep --ignore-case "$prj_url_pattern" \
        | awk -F', ' '{ print $2 }' \
        | awk '{ print $1 }'
      )"; then
        alt_homepage="$found"
        break;
      fi
    done

    # 1>&2 echo "DEBUG: project_urls='$project_urls'"
    1>&2 echo "DEBUG: alt_homepage='$alt_homepage'"
    yocto_homepage="$alt_homepage"
  fi

  declare -A lic_py2yocto=( \
    ["MIT"]="MIT" \
    ["MIT License"]="MIT" \
    ["Python Software Foundation License"]="PSF-2.0" \
  )

  declare lic_yocto_name="$license_name"
  if [[ "${lic_py2yocto["${license_name}"]+x}" = "x" ]]; then
      lic_yocto_name="${lic_py2yocto["${license_name}"]}"
  else
      1>&2 printf -- "WARNING: No matching yocto license name for '%s'.\n" \
        "$license_name"
      1>&2 printf -- " -> Keeping license name as is.\n"
      lic_yocto_name="$license_name"
  fi

  1>&2 echo "DEBUG: license_name='$license_name'"
  1>&2 echo "DEBUG: lic_yocto_name='$lic_yocto_name'"

  declare buildtool=""
  if pkg_file_content="$(exists_archive_file "$archive" "setup.py")"; then
    buildtool="setuptools"
  elif pkg_file_content="$(extract_archive_file "$archive" "pyproject.toml")"; then
    if echo "$pkg_file_content" \
      | tomlq -e '.["build-system"].["build-backend"]' > /dev/null; then
      # Uses a <https://peps.python.org/pep-0517/> build tool.
      if echo "$pkg_file_content" | tomlq -e '.tool.poetry' > /dev/null; then
        buildtool="poetry"
      elif echo "$pkg_file_content" | tomlq -e '.tool.hatch' > /dev/null; then
        buildtool="hatch"
      elif echo "$pkg_file_content" | tomlq -e '.tool.flit' > /dev/null; then
        buildtool="flit"
      fi
    fi
  fi

  declare buildtool_bbclasses=""
  if [[ "$buildtool" == "setuptools" ]]; then
    buildtool_bbclasses="setuptools3"
  elif [[ "$buildtool" == "poetry" ]]; then
    buildtool_bbclasses="python_poetry_core"
  elif [[ "$buildtool" == "hatch" ]]; then
    buildtool_bbclasses="python_hatchling"
  elif [[ "$buildtool" == "flit" ]]; then
    buildtool_bbclasses="python_flit_core"
  else
    1>&2 printf -- "WARNING: Unable to detect a compatible build tool.\n"
    1>&2 printf -- " -> Assuming setuptools.\n"
    buildtool_bbclasses="setuptools3"
  fi

  declare recipe_out_file="${recipe_out_dir}/python3-${pkg_name}_${pkg_version}.bb"

  printf -- 'SUMMARY = "%s"\n' "$summary" > "$recipe_out_file"
  printf -- 'HOMEPAGE = "%s"\n' "$yocto_homepage" >> "$recipe_out_file"
  printf -- 'LICENSE = "%s"\n' "$lic_yocto_name" >> "$recipe_out_file"
  printf -- 'LIC_FILES_CHKSUM = "file://%s;md5=%s"\n' \
    "$license_file" "$license_md5" >> "$recipe_out_file"

  printf -- "\n" >> "$recipe_out_file"
  echo "$src_uri_line" >> "$recipe_out_file"

  printf -- "\n" >> "$recipe_out_file"
  # printf -- 'PYPI_PACKAGE = "%s"\n' "$pkg_name" >> "$recipe_out_file"
  # printf -- "\n" >> "$recipe_out_file"
  printf -- "inherit pypi %s\n" "$buildtool_bbclasses" >> "$recipe_out_file"
  printf -- "\n" >> "$recipe_out_file"
  printf -- 'BBCLASSEXTEND = "native nativesdk"\n' >> "$recipe_out_file"

done < <(find "$sdist_in_dir" -mindepth 1 -maxdepth 1)
